version: '3.7'

services:
    jupyter-home:
        command: bash -c 'jupyter notebook --no-browser --ip 0.0.0.0 --allow-root --port 8888' 
        container_name: jupyter-home
        expose:
            - 8888
        image: petersontylerd/standard:latest
        ports:
            - 8888:8888
        volume:
            - {the main dir for the portfolio}:/home

something about building the image if it's not there
        